#!/usr/bin/python3
class Item:
    def __init__(self, name, quantity, price):
        self.name = name
        self.quantity = quantity
        self.price = price

    def calculator(self):
        return self.quantity * self.price


item1 = Item("coca", 20, 100)
item2 = Item("fanta", 50, 600)

print("the price of coca is" + "  " + str(item1.calculator()))
print("the price of fanta" + " " + str(item2.calculator()))
